version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    container_name: vite_frontend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/controle-hctco
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 040906
    depends_on:
      - db
    container_name: java_backend
    restart: unless-stopped

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: controle-hctco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 040906
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: postgres_db

volumes:
  pgdata:
